import { jsPDF } from "jspdf";
import { AnalysisResult, User } from "../types";

export const reportService = {
  generateClinicalReport: (result: AnalysisResult, user: User, imageBase64: string | null) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let yPos = 20;

    // Header
    doc.setFontSize(22);
    doc.setTextColor(13, 148, 136); // Medical-600
    doc.text("DermaScan AI - Clinical Report", margin, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, margin, yPos);
    doc.text(`Patient/User: ${user.name}`, margin, yPos + 5);
    doc.text(`ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, margin, yPos + 10);
    yPos += 20;

    // Divider
    doc.setDrawColor(200);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    // Primary Diagnosis
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Primary Diagnosis", margin, yPos);
    yPos += 10;

    doc.setFontSize(24);
    doc.setTextColor(result.severity === 'high' ? 220 : 0, result.severity === 'high' ? 20 : 0, result.severity === 'high' ? 60 : 0);
    doc.text(result.category, margin, yPos);
    
    // Confidence Badge
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Confidence: ${result.confidence}% (${result.confidence < 60 ? 'Uncertain' : 'High'})`, margin + 120, yPos);
    yPos += 15;

    // Image (if available)
    if (imageBase64) {
        try {
            // Keep aspect ratio max width 80
            const imgProps = doc.getImageProperties(imageBase64);
            const imgWidth = 80;
            const imgHeight = (imgProps.height * imgWidth) / imgProps.width;
            doc.addImage(imageBase64, 'JPEG', margin, yPos, imgWidth, imgHeight);
            
            // Add note next to image
            doc.setFontSize(10);
            doc.setTextColor(60);
            doc.text("Lesion Capture", margin, yPos + imgHeight + 5);
            
            yPos += imgHeight + 20;
        } catch (e) {
            console.error("Error adding image to PDF", e);
            doc.text("[Image processing failed]", margin, yPos);
            yPos += 20;
        }
    }

    // Clinical Analysis
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("Clinical Feature Analysis", margin, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setTextColor(50);
    const splitDesc = doc.splitTextToSize(result.description, pageWidth - (margin * 2));
    doc.text(splitDesc, margin, yPos);
    yPos += (splitDesc.length * 5) + 10;

    // Probability Table
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("Differential Diagnosis Probabilities", margin, yPos);
    yPos += 10;

    if (result.probabilities) {
        doc.setFontSize(10);
        Object.entries(result.probabilities)
            .sort(([,a], [,b]) => b - a)
            .forEach(([name, score]) => {
                doc.setTextColor(50);
                doc.text(name, margin, yPos);
                doc.text(`${score}%`, pageWidth - margin - 20, yPos);
                doc.setDrawColor(230);
                doc.line(margin, yPos + 2, pageWidth - margin, yPos + 2);
                yPos += 7;
            });
    }
    yPos += 10;

    // Recommendation
    doc.setFillColor(240, 253, 250); // Light teal bg
    doc.rect(margin, yPos, pageWidth - (margin * 2), 30, 'F');
    
    doc.setFontSize(12);
    doc.setTextColor(13, 148, 136);
    doc.text("AI Recommendation", margin + 5, yPos + 8);
    
    doc.setFontSize(10);
    doc.setTextColor(0);
    const splitRec = doc.splitTextToSize(result.recommendation, pageWidth - (margin * 2) - 10);
    doc.text(splitRec, margin + 5, yPos + 16);

    // Footer Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(150);
    const disclaimer = "DISCLAIMER: This report is generated by an AI system (HAM10000 model). It is NOT a definitive medical diagnosis. Please consult a certified dermatologist for professional evaluation.";
    doc.text(disclaimer, margin, 280, { maxWidth: pageWidth - (margin * 2) });

    doc.save(`DermaScan_Report_${Date.now()}.pdf`);
  }
};